version: '3'

services:
  pg:
    container_name: pg
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      PGPASSWORD: password123
      POSTGRES_DB: testdb
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
